# Generated by Django 3.1.5 on 2021-02-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_notfiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfiction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notfiction', to='profiles.profile'),
        ),
    ]
