# Generated by Django 3.1.5 on 2021-02-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_notfiction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notfiction',
            new_name='Notification',
        ),
    ]
