# Generated by Django 3.1.5 on 2021-02-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210216_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='clear',
            new_name='is_seen',
        ),
    ]
