# Generated by Django 3.1.5 on 2021-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210216_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='note',
        ),
        migrations.AddField(
            model_name='notification',
            name='note',
            field=models.CharField(blank=True, choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow')], max_length=50, null=True),
        ),
    ]
