# Generated by Django 3.1.5 on 2021-02-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210216_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='note',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='not_type',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Comment', 'Comment'), ('Follow', 'Follow')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='profiles.profile'),
        ),
    ]
